### PR TITLE
feat: add file download support

### PR DESCRIPTION
**Pull request by wongsyrone**
feat: backend: new api to download file such as planet

/PROJECT/frontend/down_folder/
http://locahost:4000/downfile/:downfilename

feat: frontend: add file download component for ease of use

Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

No download support

## What is the new behavior?

- Drop files you want to download into folder: `/PROJECT/frontend/down_folder/`
- If no token is provided, reject with 401 Unauthorized.
- After logging in, an input file that the user wants to download, such as the planet file for pure self-hosting controller.
- Prompt a dialog to download the file
- Advanced users can construct the request manually.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Testing docker image: https://hub.docker.com/r/wongsyrone/ztcontrollerzerouiwithplanetpatch

Example Usage:

```
docker run --rm -d -ti --name myztcontroller -v /root/zt-controller-docker/identity.public:/app/config/identity.public -v /root/zt-controller-docker/identity.secret:/app/config/identity.secret -v /root/zt-controller-docker/authtoken.secret:/app/config/authtoken.secret -v /root/zt-controller-docker/planet:/app/config/planet -v/root/zt-controller-docker/controller.d:/app/config/controller.d -v/root/zt-controller-docker/zero-ui-db.json:/app/backend/data/db.json -e ZU_SECURE_HEADERS=false -e ZT_PRIMARY_PORT=9993 -e ZU_CONTROLLER_ENDPOINT=http://127.0.0.1:9993/ -e ZU_DEFAULT_USERNAME=admin -e ZU_DEFAULT_PASSWORD=zero-ui -p 3000:3000 -p 4000:4000 -p 9993:9993 -p 9993:9993/udp wongsyrone/ztcontrollerzerouiwithplanetpatch:latest
```

### CODE REVIEW

**Comment by dec0dOS** [comment]
Hello, @wongsyrone!

I don't think that such a feature should be included at the application level. Serving user-specific files should be made at the web-server level. Setting up caddy/nginx/apache is way better solution for downloading user-specified files.

**Comment by wongsyrone** [comment]
@dec0dOS 

Setting web servers is not out of the box and it's not easy to ensure access control.

**Comment by dec0dOS** [comment]
Thanks for clarifying, @wongsyrone.

Anyway, I could not accept the PR in its current state. Such functionality should be hidden under the ENV flag properly and the explanation with the use cases of this feature. Could you provide a detailed way on how you use this feature and why?

**Comment by wongsyrone** [comment]
I'm not familiar with the Node.js tech stack, it's the best I can do. If you cannot merge, I'll keep this as my fork.

**Pull request closed without merging**
