### PR TITLE
Add capabilities and tags support

### PR DESCRIPTION
**Pull request by snachx**
## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #35 

## What is the new behavior?

- capabilities and tags will be parsed correctly in the flow rule editor.
- capabilities and tags can be edited in the member's setting dialog.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Please see Issue #35

### CODE REVIEW

**Comment by dec0dOS** [comment]
Hello, @snachx!
Wow, that's a great change, thank you.

**Comment by snachx** [comment]
@dec0dOS 

Also, the Dockfile needs some changes to build the image successfully, because the latest current-alpine tag bumps node version to v17, you can check the issue https://github.com/webpack/webpack/issues/14532.

I changed it to lts-alpine which uses v16 in my local environment, but I think it's not in the scope of this pr.

**Comment by dec0dOS** [comment]
I've found several bugs, need to test the pull request better before the merge. 

screen_zu

**Comment by snachx** [comment]
@dec0dOS sorry, my mistake, those two additional keys for tags and capabilities are added permantly after the first time you define them, I forgot to test on a clean environment, I'll fix it.

**Comment by snachx** [comment]
@dec0dOS I think the bug you mentioned should have been fixed now, please check it again, thanks.

**Comment by dec0dOS** [comment]
It works great!
Thank you for your contribution @snachx.

**Comment by snachx** [comment]
@dec0dOS I noticed that you added a placeholder to the input element，that's fine but it should be “tag value“ instead of “tag enum id”. A Tag has an id, some enums and flags, the final value was calculated from the selected enum and checked flags. It's a little confusing, you can check the detail in the official docs.
https://docs.zerotier.com/zerotier/rules/#33tagsaname3_3a
https://docs.zerotier.com/zerotier/rules/#342ruledefinitionlanguagesyntaxaname3_4_2a

**Comment by dec0dOS** [comment]
Thanks for your remark. I'll change it to "Tag Value".

I'm open to your additional suggestions and changes to the codebase, as you have a good understanding of the ZeroUI project and ZeroTier itself.

Currently, I don't have much time to support the ZeroUI, but I'd like to make the huge refactor in the build tools and migrate to the new versions of current packages. And fix the current issues, of course.

**Pull request merged**
